org: h4ck0rs
app: secrush
service: serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  logs:
    restApi: false
  environment:
    MONGODB_URI: ${file(./cloud-deploy-env.yml):MONGODB_URI} # Load environment variables from env.yml
    NODE_ENV: ${file(./cloud-deploy-env.yml):NODE_ENV, 'production'} # Default to 'production' if not set

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /{proxy+} # Capture all routes
          method: any



