org: h4ck0rs
app: secrush
service: serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  logs:
    restApi: false
  environment:
    MONGODB_URI: ${file(./cloud-deploy-env.yml):MONGODB_URI} # Load environment variables from env.yml
    NODE_ENV: ${file(./cloud-deploy-env.yml):NODE_ENV, 'production'} # Default to 'production' if not set

functions:
  app:
    handler: dist/app.handler # Path to the bundled handler
    events:
      - http:
          path: /{proxy+} # Capture all routes
          method: any

package:
  individually: true # Packages each function individually (good for optimized deployment)
  patterns:
    - dist/** # Include only the dist directory
    - cloud-deploy-env.yml # Include environment variable file
    - "!node_modules/**" # Exclude node_modules (if not needed by the Lambda runtime)
    - "!**/*.spec.js" # Exclude test files
    - "!**/*.log" # Exclude log files
