org: h4ck0rs
app: secrush
service: serverless-app

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  logs:
    restApi: false
  environment:
    MONGODB_URI: ${file(./cloud-deploy-env.yml):MONGODB_URI}
    NODE_ENV: ${file(./cloud-deploy-env.yml):NODE_ENV, 'production'}

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin:
              - 'https://sec-rush.com'
              - 'https://www.sec-rush.com'
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
            allowCredentials: true

      - http:
          path: /solvePuzzle
          method: any
          cors:
            origin:
              - 'https://sec-rush.com'
              - 'https://www.sec-rush.com'
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
            allowCredentials: true

package:
  individually: true
  patterns:
    - dist/**
    - cloud-deploy-env.yml
    - "!.env"
    - "!**/*.log"
