org: h4ck0rs
app: secrush
service: serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGODB_URI: ${file(./cloud-deploy-env.yml):MONGODB_URI} # Load environment variables from env.yml
    NODE_ENV: ${file(./cloud-deploy-env.yml):NODE_ENV, 'production'} # Default to 'production' if not set

functions:
  app:
    handler: app.handler
    events:
      - httpApi:
          path: /{proxy+} # Serve all routes
          method: any

custom:
  # Optional custom variables or configuration
  stages:
    dev:
      region: us-east-1
    prod:
      region: us-west-2

